### PR TITLE
Regular expression support for redirects

### PR DESCRIPTION
**Pull request by lewiscollard**
This only has an effect if `REDIRECTS_ENABLE_REGEX` is set to True in the settings. It'll effectively work the old way if it is not.

If regex redirects are enabled, then all redirects are fetched from the database and checked for a regular expression match (if they have the 'Regular expression' field set to True). This need not be slow unless there are vast numbers of redirects (but to avoid breaking any existing sites, regex-redirects is turned off by default). Of course, a side effect is that this reduces the number of redirects that will be necessary :)

Bonus changes:
- Simplify check around `settings.APPEND_SLASH` in the middleware.
- Move to Django migrations. (There are two migrations, to permit existing installations to be migrated with `--fake-initial`.)
- Validate that `old_path` starts with a forward slash.

### CODE REVIEW

**Comment by lewiscollard** [comment]
Also, as adding this feature makes this code somewhat more complex, I'm happy to write unit tests and for you to require such as a prerequisite for merging. :)

**Comment by danielsamuels** [comment]
I'd be interested in knowing what the current coverage is? I'm sure it's fairly high already.

**Comment by lewiscollard** [comment]
```
~/Code/cms-redirects/redirects $ ls -l tests
ls: tests: No such file or directory
```

:)

**Comment by danielsamuels** [comment]
Off you go then. ;)

**Comment by lewiscollard** [comment]
There we go, unit tested. Coverage is/should be 100% (but django-nose is smoking something and doesn't think that non-method attributes are tested).

Looks OK?

**Comment by danielsamuels** [comment]
Nice, I'll see if I can get it setup with Circle or Travis.

**Pull request merged**
